### ISSUE TITLE
大型项目里的数据状态混乱怎么解决

### ISSUE THREAD

**Issue by HuangLotus** [HuangLotus/move-forward#15]
今天总结一下项目中数据的流动部分的一些问题及其解决方法。
### 第一种业务场景
1. 基于angularjs框架的项目；
2. 当前模块减少对外部模块的依赖，当需要外部模块的数据时，在当前模块直接将外部模块的数据请求部分复制过来，然后在当前模块发出请求；
2. 缺点就是同一个数据如果在多个模块中需要用到时，需要在多个模块复制同一份代码，而且如果遇到需要删除某个模块的时候，就更加不方便了，容易遗漏删掉某一份代码；

上面这种场景的出发点就是为了尽可能的减少大型项目里的数据依赖复杂度而做的一种改进尝试。
但是当我被要求去这样写的时候，我发现各种不对，尤其是我习惯模块化，组件化写法的时候，这样写尤其别扭和难受。
那这其实就引出一个问题：大型项目里的数据状态依赖混乱怎么解决？

#### 大型项目里的数据状态混乱怎么解决
大型复杂项目里的数据状态混乱，比如多是由框架的数据双向绑定带来的，比如angularjs的双向绑定。
那怎么解决呢？想象一下，一个A模块的数据，被B模块引用，B又被C模块引用，C模块改变了A模块的数据，D模块又引用了B模块，D又改变了A模块的数据……乱了乱了。项目复杂到一定程度，数据的流动绝对像一张网一样。

你改动一处数据，可能会影响到别的模块和组件，这种未知的风险会给开发维护人员带来很大的心理负担。

所以怎么解决呢？
1. 既然是双向绑定带来的，那就避免双向绑定，取而代之的是引入状态管理；
2. 同时减少不必要的全局状态；
3. 重新梳理代码，让每个状态影响到的组件最少；
4. 新写的模块内部处理好自身的状态，按最佳实践来；
5. 最后以上都不行，那就只有重构代码；

后面会提到vue在不同组件间强制使用单向数据流，这使应用中的数据流更加清晰易懂，能很好的避免以上angularjs中的数据双向绑定带来的问题。

说到这里，我们发现现在流行的三大框架，数据要么单向要么双向绑定，那么他们的区别呢？

angular | vue | react
-- | -- | --
数据双向绑定 | 数据双向绑定（在单个组件里） | 数据是单向绑定
双向绑定被认为是不安全的，特别是在大型应用里 | Vue 在不同组件间强制使用单向数据流，这使应用中的数据流更加清晰易懂 | React 的设计在于它的纯净以及干净的单向数据流
开发中经常迷失在指令和作用域里 | 在拆分组件的时候，会经常用到单向数据流和回调传递 | MobX把react变成了Angular,因为他使用了双向绑定

双向数据流的代码可读性确实不是很好，而 Angular 1 的双向绑定尤其糟糕。
### 第二种业务场景

1. 功能完全模块化，其他地方需要引用就直接引入该模块。

2. 那在系统业务逻辑特别复杂的场景下，那模块之间的相互引用，会导致数据可能看起来像一张网一样混乱，那这种情况下其实就可能出现很多不可期的问题。

上面这种场景其实就是模块循环加载引用的问题，那这种情况下数据如何管理呢？

#### 模块循环加载引用

看下两段代码：

> commonjs：let { stat, readFile } = require(‘fs’) //是整体加载fs模块，这是运行时加载。
>
> es6: import { stat, readFile ] from ‘fs’ //实质是从fs模块加载3个方法，这是编译时加载

那其实背后的原理是：
1. commonjs模块输出的是一个值的拷贝，而es6模块输出的是值的引用。 
2. commonjs模块输出的是值的拷贝，也就是说一旦输出一个值，模块内部的变化就影响不到这个值。 
3. es6模块他遇到模块加载命令Import时不会去执行模块，只会生成一个动态的只读引用，等到真的需要用到时，再到模块中取值。所以es6模块是动态引用，模块里面的变量绑定其所在的模块。 
4. require命令第一次加载该脚本就会执行整个脚本，然后在内存中生成一个对象。以后需要用到这个模块时，就会到exports属性上取值，即使再次执行require命令，也不会再次执行该模块，而是到缓存中取值。特点是加载时执行，即脚本代码在requie时就会全部执行。

那两种模块加载的方式：
1. commonjs的做法是一旦出现某个模块被循环加载，就只输出已经执行的部分，还未执行的部分不输出。
2. es6模块是动态引用，遇到模块加载命令import时不会去执行模块，只是生成一个指向被加载模块的引用，需要开发者自己保证真正取值时能够取到值。es6模块中，只要引用是存在的，代码就能执行。

所以针对模块循环加载引用的情况，在我们的前端代码里如果是用的commonjs规范，那可能就会有问题；
但是如果用的es6模块规范，取值的结果正确与否需要开发者自己去保证。

#### 总结
今天关于数据的总结就是以上，所以我们在做开发的时候，无论是选择哪种框架，在一开始的规划上都要想清楚，数据部分是怎么处理，避免项目做大后，数据流向混乱的局面。

**Comment by xiaokeqi** [comment]
👍棒
