### ISSUE TITLE
那些和数组相关的知识点

### ISSUE THREAD

**Issue by HuangLotus** [HuangLotus/move-forward#8]
## 如何判断一个数组

对于一些基本类型，typeof是可以判断出数据类型，但是判断一些引用类型时候，就不行了，比如：

```javascript
typeof [1,2,3] // object
```

很多情况下可以这样来判断：

```javascript
var obj = [1,2,3];
obj instanceof Array; //return true 
obj.constructor == Array; // return true
```

但是如果在不同的环境下，上面这段代码可能得到false的结果。

如果网页中包含多个全局环境（比如iframe），那实际上就存在两个以上不同的全局执行环境，从而存在两个以上不同版本的Array构造函数。

instanceof操作符的它假定只有一个全局环境，因为instanceof判断就是在当前全局作用域的原型链上去寻找__proto__  直到找到为止.

而constructor在于可以被改写：

```javascript
var str = 'abc';    
str.constructor = Array;
str.constructor === Array // return true
```

很明显，这样判断其实也不准确。

那最后其实比较可靠的方法有：

```javascript
if（Array.isArray(value)）{
    return true;
}
```

以及：

```javascript
Object.prototype.toString.call(arg)==='[object Array]'
```

## 写一个将多维数组展开的方法

**Comment by xiaokeqi** [comment]
用reduce实现map
console.log(arr.myMap((item, index) => index * 2));
输出  [NaN, NaN, NaN, NaN, NaN]
没有考虑其他参数情况

**Comment by HuangLotus** [comment]
> console.log(arr.myMap((item, index) => index * 2));



> 用reduce实现map
> console.log(arr.myMap((item, index) => index * 2));
> 输出  [NaN, NaN, NaN, NaN, NaN]
> 没有考虑其他参数情况

是的，基本只实现了核心功能，其他参数没考虑进来，刚才已经改了哈~
